# Generated by Django 5.0.3 on 2024-04-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='Deadline time/date(example:2024-12-31:'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
