# Generated by Django 5.0.3 on 2024-04-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_purchase_date_alter_purchase_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='image',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='Deadline time/date(example:2024-12-31):'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(blank=True, null=True, upload_to='')),
                ('rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchase')),
            ],
        ),
    ]
