# Generated by Django 5.0.3 on 2024-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_purchase_image_alter_purchase_date_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
