# Generated by Django 5.0.3 on 2024-05-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_purchase_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='Deadline time/date(example:2012-03-13 21:12:20):'),
        ),
    ]
