# Generated by Django 5.0.3 on 2024-04-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_purchase_imag_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='imag',
            new_name='image',
        ),
    ]
